### PR TITLE
Added Issue_template 

### LINKED ISSUE #4: Add github issue template
Copy the github issue template from Accessible Web Dev and make any adjustments to links/names as necessary.

### PR DESCRIPTION
**Pull request by wasup-yash**
Added issue template files for the Bug reports and Feature request

Motivation for the change:
Closes #4

### CODE REVIEW

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Thank you. This is almost ready, just one small change. It's important that the folder is in uppercase (github conventions) so please update the folder to be called `ISSUE_TEMPLATE`

**Comment by wasup-yash** [comment]
> Thank you. This is almost ready, just one small change. It's important that the folder is in uppercase (github conventions) so please update the folder to be called `ISSUE_TEMPLATE`

oh, I didn't knew about that thanks for pointing it out.

**Comment by wasup-yash** [comment]
Hey, the folder name is not updated as it doesn't count as a commit so do I need to delete the folder and create a new folder with the name `ISSUE_TEMPLATE` and add respective files to it?

**Comment by EmmaDawsonDev** [comment]
Hmm, git sometimes ignores it if you just change the casing. Try renaming the current folder to something else, commit it, then rename it again to what it should be then commit add and push

**Comment by wasup-yash** [comment]
Hey, I renamed the folder, but I did it without the signed-off(verification) message is it fine or do I need to commit again as it will create one more commit in history so it is not necessary as I think, what do you say?

**Comment by EmmaDawsonDev** [comment]
It should be fine, thanks!

**Pull request merged**
